name: run extract_cv.py

on:
  schedule:
    - cron: '8 20 * * 1' # 
    
env:
  SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # install the python version needed and dependencies
      - run: pip install beautifulsoup4 requests google-search-results

      - name: execute py script # run extractor from Scholar
        run: |
          set -e  # exit if any command fails
          python code/generate_publication.py
          git config --global user.name "github-actions"
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "update publications page" || echo "No changes to commit"
          git push
